# Generated by Django 4.0.6 on 2022-07-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0003_alter_video_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
