# Generated by Django 4.0.6 on 2022-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0005_video_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_length',
            field=models.TextField(editable=False, null=True),
        ),
    ]
