# Generated by Django 4.0.6 on 2022-07-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0006_video_video_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_size',
            new_name='video_size_in_mb',
        ),
    ]
