# Generated by Django 4.0.6 on 2022-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0007_rename_video_size_video_video_size_in_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_size_in_mb',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
