# Generated by Django 4.0.6 on 2022-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0009_alter_video_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.TextField(editable=False, null=True),
        ),
    ]
